import React, { Fragment } from "react";
import Head from "next/head";
import ApplicationBar from "../ApplicationBar/ApplicationBar";
import Container from "@mui/material/Container";

type Props = {
  children: JSX.Element;
};

const Layout: React.FC<Props> = (props) => {
  return (
    <Fragment>
      <Head>
        <title>Productivity App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApplicationBar />
      <Container sx={{ paddingTop: "10px" }}>
        <main>{props.children}</main>
      </Container>
    </Fragment>
  );
};

export default Layout;
